name: R-CMD-check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.R_LIBS_USER }}
          /usr/local/lib/R/site-library
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/NAMESPACE') }}
        restore-keys: |
          ${{ runner.os }}-r-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install CRAN and Bioconductor dependencies
      run: |
        Rscript -e 'install.packages(c("remotes", "testthat", "knitr", "rmarkdown", "Matrix", "Seurat"), dependencies = TRUE)'
        Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")'
        Rscript -e 'BiocManager::install(c("SingleCellExperiment", "SummarizedExperiment"), ask = FALSE)'

    - name: R CMD check
      run: R CMD check --as-cran .

    
